version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.19.0
    steps:
      - checkout
      - run: node -v
      - run:
          name: Check Node literal
          shell: node
          command: | 
            const util = require('util');
            const na = "custom_error";
            const na_custom_message = util.format('\x1b[31m%s\x1b[0m', `${na}!`);
            const custom_message = util.format('\x1b[31mcustom_error!\x1b[0m');
            console.log(na_custom_message);
            console.log(custom_message);
            console.log(na_custom_message === custom_message);
      - run:
          name: Check Node addition to string
          shell: node
          command: | 
             const na = "la"
             console.log("aa" + na)
